shop_lileya_homepage:
    path:     /
    defaults: { _controller: ShopLileyaBundle:Page:index }
    requirements:
        _method:  GET
shop_lileya_about:
    pattern:  /about
    defaults: { _controller: ShopLileyaBundle:Page:about }
    requirements:
        _method:  GET
shop_lileya_contact:
    pattern:  /contact
    defaults: { _controller: ShopLileyaBundle:Page:contact }
    requirements:
        _method:  GET|POST