ShopLileyaBundle_homepage:
   pattern: /
   defaults: { _controller: ShopLileyaBundle:Page:index }
   requirements:
       _method: GET
ShopLileyaBundle_contact:
   pattern: /contact
   defaults: { _controller: ShopLileyaBundle:Page:contact }
   requirements:
       _method: GET|POST
ShopLileyaBundle_product_show:
    pattern: /product/show/{id}
    defaults: {_controller:ShopLileyaBundle:Product:show}
    requirements:
        _methd: GET
        id: \d+
ShopLileyaBundle_product:
    pattern: /product/{category}/{subcategory}/{style}
    defaults: {_controller:ShopLileyaBundle:Product:index, category :NULL, subcategory:NULL, style:NULL}
    requirements:
        _methd: GET
        
ShopLileyaBundle_comment_create:
    pattern: /comment/{product_id}
    defaults: {_controller:ShopLileyaBundle:Comment:create}
    requirements:
        _metod: POST
        blog_id: \d+
ShopLileyaBundle_corf_add:
    pattern: /corf/add
    defaults: {_controller:ShopLileyaBundle:Corf:add}
    requirements:
        _metod: GET|POST
       
login:
    pattern:   /login
    defaults:  { _controller: ShopLileyaBundle:Security:login }
login_check:
    pattern:   /login_check