<?php

namespace Shop\LileyaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getIdCategory($url){
        $qp=  $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.nav=:url')
                ->setParameter('url',$url);
        return $qp->getQuery()
                ->getResult();
    }
}
