<?php

namespace Shop\LileyaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LileyaRepository extends EntityRepository
{
    public function getLatersProducts($limit=null){
        $qp=  $this->createQueryBuilder('p')
                ->delect('p')
                -addOrderBy('p.id','DESC');
        if(false===is_null($limit))
            $qp->setMaxResult($limit);
        return $qp->getQuery()->getResult();
    }
}
