<?php

namespace Shop\LileyaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
     public function getLatestProducts($category=NULL,$subcategory=NULL){
        $qp=  $this->createQueryBuilder('p')
                ->select('p')
                ->addOrderBy('p.id','DESC');
        if(false===is_null($category))
            $qp->where('p.category=:category_id')
            ->setParameter('category_id',$category);
            if(false===is_null($subcategory))
            $qp->andWhere('p.subcategory_id=:subcategory_id')
            ->setParameter('subcategory_id',$subcategory);
        return $qp->getQuery()->getResult();
    }
}
