<?php

namespace Shop\LileyaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends EntityRepository
{
    public function getIdSubCategory($url)
    {
        $qp = $this->createQueryBuilder('c')->select('c')->where('c.nav=:url')->
            setParameter('url', $url);
        return $qp->getQuery()->getResult();
    }
}
